### PR TITLE
Feat: Load websockets automaticly

### PR DESCRIPTION
**Pull request by martvdm**

### CODE REVIEW

**Comment by timjans01** [comment]
Best practice to add a default JWT token in the .env example file

**Comment by martvdm** [comment]
> 

JWT is not in use anymor mister tim guy

**Comment by timjans01** [comment]
> > 
> 
> JWT is not in use anymor mister tim guy

Then should it still be defined in the example?

**Comment by martvdm** [comment]
> > > 
> > 
> > JWT is not in use anymor mister tim guy
> 
> Then should it still be defined in the example?

No

**Review by DanericNetwork — APPROVED** [review]

**Pull request merged**
